---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: instalar paquete de Apache
      package:
        name: httpd
        state: latest
      tags: install  
    - name: levantar servicio y hacerlo persistente al reboot 
      service:
        name: httpd
        state: started
        enabled: yes
      tags: config  
    - name: crear fichero index vacio
      file:
        path: /var/www/html/index.html
        state: touch
      tags: config  
    - name: añadir contenido a index.hmtl
      copy:
        content: "Hello world!! Hola mon!!"
        dest: /var/www/html/index.html
      tags: config
    - name: uninstall apache
      package: 
        name: httpd
        state: absent
      tags: never,uninstall
